<?php
namespace Hamahang\LTM\Database\Seeds;

use Illuminate\Database\Seeder;

class ProvinceTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('ltm_provinces')->delete();

        \DB::table('ltm_provinces')->insert(array (
            0 =>
            array (
                'id' => 1,
                'center_city_id' => NULL,
                'name' => 'اردبيل',
                'center_city_name' => 'اردبيل',
                'code' => 350000,
                'code_clear' => 25,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            1 =>
            array (
                'id' => 2,
                'center_city_id' => NULL,
                'name' => 'اصفهان',
                'center_city_name' => 'اصفهان',
                'code' => 130000,
                'code_clear' => 3,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            2 =>
            array (
                'id' => 3,
                'center_city_id' => NULL,
                'name' => 'البرز',
                'center_city_name' => 'كرج',
                'code' => 410000,
                'code_clear' => 31,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            3 =>
            array (
                'id' => 4,
                'center_city_id' => NULL,
                'name' => 'ايلام',
                'center_city_name' => 'ايلام',
                'code' => 140000,
                'code_clear' => 21,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            4 =>
            array (
                'id' => 5,
                'center_city_id' => NULL,
                'name' => 'آذربايجان شرقي',
                'center_city_name' => 'تبريز',
                'code' => 110000,
                'code_clear' => 1,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            5 =>
            array (
                'id' => 6,
                'center_city_id' => NULL,
                'name' => 'آذربايجان غربي',
                'center_city_name' => 'اروميه',
                'code' => 120000,
                'code_clear' => 2,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            6 =>
            array (
                'id' => 7,
                'center_city_id' => NULL,
                'name' => 'بوشهر',
                'center_city_name' => 'بوشهر',
                'code' => 160000,
                'code_clear' => 15,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            7 =>
            array (
                'id' => 8,
                'center_city_id' => NULL,
                'name' => 'تهران',
                'center_city_name' => 'تهران',
                'code' => 170000,
                'code_clear' => 24,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            8 =>
            array (
                'id' => 9,
                'center_city_id' => NULL,
                'name' => 'چهار محال و بختياري',
                'center_city_name' => 'شهر كرد',
                'code' => 180000,
                'code_clear' => 16,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            9 =>
            array (
                'id' => 10,
                'center_city_id' => NULL,
                'name' => 'خراسان جنوبي',
                'center_city_name' => 'بيرجند',
                'code' => 400000,
                'code_clear' => 29,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            10 =>
            array (
                'id' => 11,
                'center_city_id' => NULL,
                'name' => 'خراسان رضوي',
                'center_city_name' => 'مشهد',
                'code' => 190000,
                'code_clear' => 4,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            11 =>
            array (
                'id' => 12,
                'center_city_id' => NULL,
                'name' => 'خراسان شمالي',
                'center_city_name' => 'بجنورد',
                'code' => 390000,
                'code_clear' => 30,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            12 =>
            array (
                'id' => 13,
                'center_city_id' => NULL,
                'name' => 'خوزستان',
                'center_city_name' => 'اهواز',
                'code' => 200000,
                'code_clear' => 5,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            13 =>
            array (
                'id' => 14,
                'center_city_id' => NULL,
                'name' => 'زنجان',
                'center_city_name' => 'زنجان',
                'code' => 210000,
                'code_clear' => 17,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            14 =>
            array (
                'id' => 15,
                'center_city_id' => NULL,
                'name' => 'سمنان',
                'center_city_name' => 'سمنان',
                'code' => 220000,
                'code_clear' => 22,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => '2014-07-07 12:38:36',
                'deleted_at' => Null,
            ),
            15 =>
            array (
                'id' => 16,
                'center_city_id' => NULL,
                'name' => 'سيستان و بلوچستان',
                'center_city_name' => 'زاهدان',
                'code' => 230000,
                'code_clear' => 6,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            16 =>
            array (
                'id' => 17,
                'center_city_id' => NULL,
                'name' => 'فارس',
                'center_city_name' => 'شيراز',
                'code' => 240000,
                'code_clear' => 7,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            17 =>
            array (
                'id' => 18,
                'center_city_id' => NULL,
                'name' => 'قزوين',
                'center_city_name' => 'قزوين',
                'code' => 370000,
                'code_clear' => 27,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            18 =>
            array (
                'id' => 19,
                'center_city_id' => NULL,
                'name' => 'قم',
                'center_city_name' => 'قم',
                'code' => 360000,
                'code_clear' => 26,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            19 =>
            array (
                'id' => 20,
                'center_city_id' => NULL,
                'name' => 'كردستان',
                'center_city_name' => 'سنندج',
                'code' => 250000,
                'code_clear' => 13,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            20 =>
            array (
                'id' => 21,
                'center_city_id' => NULL,
                'name' => 'كرمان',
                'center_city_name' => 'كرمان',
                'code' => 260000,
                'code_clear' => 8,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            21 =>
            array (
                'id' => 22,
                'center_city_id' => NULL,
                'name' => 'كرمانشاه',
                'center_city_name' => 'كرمانشاه',
                'code' => 150000,
                'code_clear' => 9,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            22 =>
            array (
                'id' => 23,
                'center_city_id' => NULL,
                'name' => 'كهگيلويه و بويراحمد',
                'center_city_name' => 'ياسوج',
                'code' => 270000,
                'code_clear' => 23,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            23 =>
            array (
                'id' => 24,
                'center_city_id' => NULL,
                'name' => 'گلستان',
                'center_city_name' => 'گرگان',
                'code' => 380000,
                'code_clear' => 28,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            24 =>
            array (
                'id' => 25,
                'center_city_id' => NULL,
                'name' => 'گيلان',
                'center_city_name' => 'رشت',
                'code' => 280000,
                'code_clear' => 10,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            25 =>
            array (
                'id' => 26,
                'center_city_id' => NULL,
                'name' => 'لرستان',
                'center_city_name' => 'خرم آباد',
                'code' => 290000,
                'code_clear' => 18,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            26 =>
            array (
                'id' => 27,
                'center_city_id' => NULL,
                'name' => 'مازندران',
                'center_city_name' => 'ساري',
                'code' => 300000,
                'code_clear' => 11,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            27 =>
            array (
                'id' => 28,
                'center_city_id' => NULL,
                'name' => 'مركزي',
                'center_city_name' => 'اراك',
                'code' => 310000,
                'code_clear' => 12,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            28 =>
            array (
                'id' => 29,
                'center_city_id' => NULL,
                'name' => 'هرمزگان',
                'center_city_name' => 'بندر عباس',
                'code' => 320000,
                'code_clear' => 14,
                'version' => '0',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            29 =>
            array (
                'id' => 30,
                'center_city_id' => NULL,
                'name' => 'همدان',
                'center_city_name' => 'همدان',
                'code' => 330000,
                'code_clear' => 19,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
            30 =>
            array (
                'id' => 31,
                'center_city_id' => NULL,
                'name' => 'يزد',
                'center_city_name' => ' ',
                'code' => 340000,
                'code_clear' => 20,
                'version' => '1',
                'is_active' => '1',
                'created_by' => 0,
                'created_at' => Null,
                'updated_at' => Null,
                'deleted_at' => Null,
            ),
        ));


    }
}
